# 민간행사보조금 집행실태 특정감사 (인천광역시, 2025)
# docs/민간행사보조금_감사사례_체크리스트.md

EVENT_AUDIT_ITEMS: dict[str, list[dict[str, str]]] = {
    "1": [
        {"category": "교부신청", "item_content": "민간행사보조금 사업계획서에 행사 목적·일정·예산이 구체적으로 명시되어 있는가?",
         "judge_criteria": "행사 지원 적정성", "law_ref": "지방보조금 관리기준", "risk_level": "M", "case_ref": "처분1·분할발주"},
        {"category": "교부결정", "item_content": "교부결정 전 자부담금 예치 여부를 확인하였는가?",
         "judge_criteria": "교부 전 자부담 예치", "law_ref": "충남 업무운영지침 제15조", "risk_level": "H", "case_ref": "처분3"},
        {"category": "교부결정", "item_content": "수익금 반환 교부 조건이 교부결정서에 명시되어 있는가?",
         "judge_criteria": "수익금 반환 조건", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제9조", "risk_level": "H", "case_ref": "처분10"},
        {"category": "예산편성", "item_content": "민간행사사업보조(307-04)와 민간경상보조(307-02)를 구분하여 편성하였는가?",
         "judge_criteria": "행사보조 비목 구분", "law_ref": "예산편성 운영기준", "risk_level": "H", "case_ref": "민간행사감사"},
        {"category": "교부결정", "item_content": "3억 원 이상 사업에 감사인 실적보고서 검증 조건이 반영되어 있는가?",
         "judge_criteria": "3억 이상 검증", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제17조", "risk_level": "H", "case_ref": "검증보고"},
        {"category": "사업자 선정", "item_content": "민간행사 지원 대상 단체의 자격·실적을 사전에 검토하였는가?",
         "judge_criteria": "보조사업자 적격성", "law_ref": "지방보조금 관리기준", "risk_level": "M", "case_ref": "감사개요"},
    ],
    "2": [
        {"category": "계약·지출", "item_content": "단일 용역을 분할 발주하여 1인 수의계약을 체결하지 않았는가?",
         "judge_criteria": "분할계약 금지", "law_ref": "지방계약법, 입찰집행기준", "risk_level": "H", "case_ref": "처분1·분할발주"},
        {"category": "계약·지출", "item_content": "추정가격 2천만 원 초과 시 2인 이상 견적 수의계약 절차를 준수하였는가?",
         "judge_criteria": "2인 견적 수의계약", "law_ref": "지방계약법 시행령 제25조", "risk_level": "H", "case_ref": "처분2·1인수의"},
        {"category": "용도·변경", "item_content": "지방보조금 전용계좌를 별도 개설·운용하고 있는가?",
         "judge_criteria": "전용계좌 운용", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분4"},
        {"category": "집행기간", "item_content": "근로계약 체결 전 인건비를 보조금으로 사전 집행하지 않았는가?",
         "judge_criteria": "계약 전 인건비 집행 금지", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분13"},
        {"category": "지출방법", "item_content": "보조금 집행 시 대표자 결재 없이 지출하지 않았는가?",
         "judge_criteria": "지출결의·대표 결재", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분9"},
        {"category": "집행항목", "item_content": "행사와 무관한 기념품·경품을 보조금으로 구입하지 않았는가?",
         "judge_criteria": "목적 외 경품·기념품", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제14조", "risk_level": "H", "case_ref": "처분7"},
    ],
    "3": [
        {"category": "원천징수", "item_content": "경품·강사료 지급 시 소득세 원천징수를 이행하였는가?",
         "judge_criteria": "경품·강사 원천징수", "law_ref": "소득세법", "risk_level": "H", "case_ref": "처분6·14"},
        {"category": "증빙 완전성", "item_content": "자부담금 예치 및 지출 증빙서류를 교부 전·집행 시 확인하였는가?",
         "judge_criteria": "자부담·증빙 확인", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분11·12"},
        {"category": "증빙 적정성", "item_content": "보조금으로 구입한 온누리상품권을 별도 관리·정산하였는가?",
         "judge_criteria": "상품권 관리", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분5"},
        {"category": "증빙 대조", "item_content": "보조금 전용통장 입출금 내역과 지출결의서가 일치하는가?",
         "judge_criteria": "전용통장-결의서 대조", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분8·9"},
        {"category": "증빙 유효성", "item_content": "경품 수령자 기타소득세 납부 증빙이 구비되어 있는가?",
         "judge_criteria": "기타소득세 납부", "law_ref": "소득세법", "risk_level": "H", "case_ref": "처분14"},
        {"category": "증빙 완전성", "item_content": "인건비 지급 시 근로계약서와 실제 지급 내역이 일치하는가?",
         "judge_criteria": "근로계약-지급 대조", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분13"},
    ],
    "4": [
        {"category": "정산검사", "item_content": "실적보고서 미제출 보조사업자에 대한 조치(시정·환수)를 하였는가?",
         "judge_criteria": "미제출 시 조치", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제17조", "risk_level": "H", "case_ref": "처분8"},
        {"category": "정산검사", "item_content": "정산 검사 시 분할발주·수의계약 위반 여부를 확인하였는가?",
         "judge_criteria": "정산 시 계약 적정성", "law_ref": "지방계약법", "risk_level": "H", "case_ref": "처분1"},
        {"category": "정산검사", "item_content": "행사 무관 지출 및 증빙 미비 항목을 정산에서 제외하였는가?",
         "judge_criteria": "목적 외·증빙 미비 제외", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제20조", "risk_level": "H", "case_ref": "처분7"},
        {"category": "자부담", "item_content": "자부담금 집행 비율이 사업계획 대비 적정하며 미달 시 환수 조치하였는가?",
         "judge_criteria": "자부담 비율 정산", "law_ref": "지방보조금 관리기준", "risk_level": "H", "case_ref": "처분15"},
        {"category": "정산확정", "item_content": "3억 원 이상 사업의 감사인 검증보고서를 정산 시 확인하였는가?",
         "judge_criteria": "검증보고 확인", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제17조", "risk_level": "H", "case_ref": "검증보고"},
        {"category": "수익금", "item_content": "행사 수익금 발생 시 반환 조건에 따라 반납·정산하였는가?",
         "judge_criteria": "수익금 반환", "law_ref": "지방자치단체 보조금 관리에 관한 법률 제9조", "risk_level": "H", "case_ref": "처분10"},
    ],
}
